### ISSUE TITLE
open to PRs?

### ISSUE THREAD

**Issue by deitch** [CloudSoda/go-smb2#10]
I have been using [the lib this was based upon](https://github.com/hirochachacha/go-smb2/), but that hasn't been updated in well over a year, and issues and PRs are getting no attention.

I have just one PR for now, [making initiator members public](https://github.com/hirochachacha/go-smb2/pull/85). Are you open to pulling that in? I would be happy to open that PR to here as well.

Thanks

**Comment by arashpayan** [comment]
Hi @deitch. Yes, I'm open to accepting PRs for new functionality, and making the `Initiator` methods public sounds good.

**Comment by deitch** [comment]
First one is open at #11 

I have two follow-ups in mind:

* enable linting on PRs (that would require about 45-50 listing fixes)
* enable anonymous auth

Any objections?

**Comment by arashpayan** [comment]
Both of those sound good. :+1:

**Comment by deitch** [comment]
Great. You'll see them in the coming days.

**Comment by deitch** [comment]
#12 for lint

**Comment by arashpayan** [comment]
Linting and anonymous auth are now both in `main`.
