### ISSUE TITLE
Investigate adding kerberos authentication support

### ISSUE THREAD

**Issue by arashpayan** [CloudSoda/go-smb2#15]
It may have been successfully added in this fork: https://github.com/lorenz/go-smb2

with this commit: https://github.com/lorenz/go-smb2/commit/7a091ab768e3ed62d88a4933f65969dd2f6e05e0

citation here: https://github.com/hirochachacha/go-smb2/issues/63#issuecomment-1732749715

**Comment by jgiannuzzi** [comment]
Hi @arashpayan, I'm willing to contribute this feature (based on @lorenz's work). Would you be open to taking a dependency on https://github.com/jcmturner/gokrb5?

**Comment by lorenz** [comment]
That commit is all that's needed, it just needs to be cherry-picked into the repo (and b975b4a should be squashed into it). I didn't upstream it myself as upstream was abandoned. You probably want most of my other changes too, they fix various issues with go-smb2. Sadly this fork seems kind of abandoned as well.

**Comment by jgiannuzzi** [comment]
@lorenz I've ported your commit to work with the upstream gokrb5 as I think we should avoid replace directives when possible.
Ultimately I'd like to add Kerberos support to the smb backend of rclone, which uses this fork.

**Comment by arashpayan** [comment]
Hi @jgiannuzzi. Thank you for the offer. Adding a dependency on github.com/jcmturner/gokrb5 is fine.

@lorenz, we heavily use this package at cloudsoda.io, so we're committed to maintaining it, but we only add new features when a business need demands it. That said, we're currently working on support for reading and writing security descriptors.

**Comment by jgiannuzzi** [comment]
Thank you @arashpayan, I've raised a PR to implement this in #24.
